### ISSUE TITLE
Has anyone succesfully deployed tableau into Kubernetes 1.25, where containerd is the container runtime?

### ISSUE THREAD

**Issue by sandywangkpmg** [tableau/tableau-server-in-kubernetes#19]

**Comment by adr-xyt** [comment]
What kind of problems do you have? We are trying to run the latest version 2023.1.2 on k8s (1.23), but the server doesn't initialize. On the same machine, running the same container directly on docker (bypassing k8s), everything works without a problem.

**Comment by sandywangkpmg** [comment]
> 

we are having exact same issue, 3 services are down, cannot be initialized. After rolling backto 2022.3.6 (previous major version), it started fine. So it's not a problem with K8S version or containerd, it's something with the last major version.

**Comment by adr-xyt** [comment]
logs below: 
`Initialization Error
This job failed due to unexpected error: 'ServiceOperationTimeoutException'
One or more services failed to reach their expected state. node1: floweditor_0.20231.23.0511.1508: Failed to start. Current status: DOWN flowprocessor_0.20231.23.0511.1508: Failed to start. Current status: STATUS_UNAVAILABLE webhooks_0.20231.23.0511.1508: Failed to start. Current status: DOWN
Initialization terminated at step 35 of 42: Finalizing the topology failed.`

we're probably experiencing the same problem. I've tried to compare the container definitions on both startup methods, but I don't see any significant differences. :(

**Comment by sandywangkpmg** [comment]
> logs below: `Initialization Error This job failed due to unexpected error: 'ServiceOperationTimeoutException' One or more services failed to reach their expected state. node1: floweditor_0.20231.23.0511.1508: Failed to start. Current status: DOWN flowprocessor_0.20231.23.0511.1508: Failed to start. Current status: STATUS_UNAVAILABLE webhooks_0.20231.23.0511.1508: Failed to start. Current status: DOWN Initialization terminated at step 35 of 42: Finalizing the topology failed.`
> 
> we're probably experiencing the same problem. I've tried to compare the container definitions on both startup methods, but I don't see any significant differences. :(

yep, exact same problem. i have done some comparision too, couldn't figure out any difference between container in docker and container in K8S. 
After changing the version to 2022.3, the container started fine and initilization finished with no issue.
So my assumption is something has changed in 2023.1, the latest major version that Tableau announced it supports  Ubuntu 20.04.

**Comment by kja-xyt** [comment]
@sandywangkpmg did you manage to solve the issue?

**Comment by adr-xyt** [comment]
@sandywangkpmg it seems that version 2023.1.3 works on k8s
